# AutomateRunner docker-compose
 version: '3'
 services:
       server:
               build: .
               command: bash -c "python server/manage.py makemigrations && python server/manage.py migrate && python server/manage.py runserver 0.0.0.0:8000"
               container_name: automaterunner
               volumes:
                - ./AutomateRunner:/app
               ports:
                - "8000:8000"
        

       postgres:
               image: postgres
               restart: always
               environment:
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
               ports:
                - '5438:5432'
               volumes:
                - ./postgres-data:/var/lib/postgresql/data
